### ISSUE TITLE
需要显示每个投稿点击通过和拒绝的人的ID

### ISSUE THREAD

**Issue by LinYunerr** [taotecode/submission_robot#4]
在当前的机器人设计中，设计了2票通过/2票拒绝。现在需要在该投稿被确认通过/拒绝后，显示谁点了确认，谁点了拒绝

此内容需要以文本方式显示，方便搜索、查阅

**Comment by taotecode** [comment]
这个功能存在的
<img width="384" alt="image" src="https://github.com/taotecode/submission_robot/assets/48904825/e19dac3c-7fca-4405-a5a5-c17a82e6a558">
同时，最新版更新了排版
<img width="393" alt="image" src="https://github.com/taotecode/submission_robot/assets/48904825/03078bcf-230f-4a32-94a0-3b576046ecdc">
最新排版预计0.1.07版本更新
