### ISSUE TITLE
使用/list命令后，之前的相同内容消失。相同内容总是只显示一份

### ISSUE THREAD

**Issue by LinYunerr** [taotecode/submission_robot#7]
由于审核员出现时间不同，因此不可避免的需要使用/list功能唤起所有没有审核的提问。点击内容会导致审核群内出现多份相同投稿（之前出现的、被list命令唤起的）

希望总是只会出现一个内容，这样可以减少群中内容冗余。即，在list并点击内容后，删除之前相同的内容。

可能的实现方式：使用/list后直接发送所有没有被审核的内容，并删除之前的相同提问

**Comment by taotecode** [comment]
这个功能是这样的
只显示未审核的投稿，出现几个是根据有多少未审核的投稿来显示的

这个删除之前相同的内容是什么意思？没看懂

**Comment by taotecode** [comment]
意思就是说，点击list里面的稿件，然后把聊天记录之前的稿件审核消息全部删除，然后重新发送这个稿件的审核消息
